Valor = int(input())
Valor1 = int(input())
Valor2 = int(input())
Suma = (Valor+Valor1+Valor2) 
Restar = (Valor-Valor1)
Multiplicar = (Valor*Valor1*Valor2)
Dividir = (Valor/Valor1)
print("pepe tiene", Valor, "Euros"), print ("y Yolanda tiene", Valor1, "Euros"), print("y yo aporto", Valor2, "Euros"), print ("entre los tres tenemos", Suma, "Euros")
print("El Pepe tiene", Valor, "Euros"), print("Yolanda le a quitado", Valor1, "Euros"), print("al final Pepe le a quedado", Restar, "Euros")
print("El Pepe tiene una Caja llena de libros. En total hay", Valor, "libros"), print("Yolanda tambien tien una caja llena de libros en total tiene", Valor1, "libros"), print("yo tengo otra cja con", Valor2, "libros"), print("Entre todos tenmos", Multiplicar, "libros") 
print("El Pepe Tiene", Valor, "Galletas"), print("y lo tiene que repartir entre", Valor1, "Hijos"), print("En total de repartida entre", Dividir, "galletas para cada hijo") 
